spring:
  data:
    elasticsearch:
      cluster-nodes: localhost:9200
      repositories:
        enabled: true
      client:
        reactive: false

# Enable logging
logging:
  level:
    org.elasticsearch: DEBUG
    org.springframework.data.elasticsearch: DEBUG

# eureka configuration
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
