spring:
  data:
    elasticsearch:
      repositories:
        enabled: true

  elasticsearch:
    uris: http://localhost:9200

logging:
  level:
    org.elasticsearch: DEBUG
    org.springframework.data.elasticsearch: DEBUG

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
