apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: service-registry
  labels:
    release: prometheus-stack
spec:
  selector:
    matchLabels:
      app: service-registry
  endpoints:
    - port: http
      path: /actuator/prometheus
      interval: 15s
  namespaceSelector:
    matchNames:
      - default
